[package]
name = "wassily"
version = "0.2.0"
authors = ["jeffreyrosenbluth <jeffrey.rosenbluth@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tiny-skia = {git = "https://github.com/RazrFalcon/tiny-skia.git", branch = "master" }
noise = { git = "https://github.com/Razaekel/noise-rs.git", branch = "develop" }
rand = "0.8.3"
rand_distr = "0.4"
rand_pcg = "0.3"
palette = "0.6"
png = "0.17"
image = "0.24"
color-thief = "0.2"
num-traits = "0.2"
num-complex = "0.4"
serde_json = "1.0"
serde = {version = "1.0", features = ["derive"]}
once_cell = "1.9"