[package]
name = "wassily"
version = "0.3.0"
authors = ["jeffreyrosenbluth <jeffrey.rosenbluth@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tiny-skia = {git = "https://github.com/RazrFalcon/tiny-skia.git", branch = "master" }
noise = { git = "https://github.com/Razaekel/noise-rs.git", branch = "develop" }
rand = {version = "0.8.5", features = ["small_rng"]}
rand_distr = "0.4"
palette = "0.6"
png = "0.17"
image = "0.24"
color-thief = "0.2"
num-traits = "0.2"
num-complex = "0.4"
once_cell = "1.9"