[package]
name = "wassily"
version = "0.1.0"
authors = ["jeffreyrosenbluth <jeffrey.rosenbluth@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tiny-skia = "0.4.2"
noise = "0.7.0"
rand = "0.8.3"
rand_distr = "0.4"
rand_pcg = "0.3"
colorous = "1.0"